import maplibregl from "maplibre-gl";

export async function onMapLoad(map: maplibregl.Map) {
  const olympics = await map.loadImage("img/olympics.png");
  map.addImage("olympics", olympics.data);
  const world_championship = await map.loadImage("img/world_championship.png");
  map.addImage("world_championship", world_championship.data);
  const china_smash = await map.loadImage("img/china_smash.png");
  map.addImage("china_smash", china_smash.data);
  const saudi_smash = await map.loadImage("img/saudi_smash.png");
  map.addImage("saudi_smash", saudi_smash.data);
  const singapore_smash = await map.loadImage("img/singapore_smash.png");
  map.addImage("singapore_smash", singapore_smash.data);
  const us_smash = await map.loadImage("img/us_smash.png");
  map.addImage("us_smash", us_smash.data);
  const finals = await map.loadImage("img/finals.png");
  map.addImage("finals", finals.data);
  const champions = await map.loadImage("img/champions.png");
  map.addImage("champions", champions.data);
  const star_contender = await map.loadImage("img/star_contender.png");
  map.addImage("star_contender", star_contender.data);
  const contender = await map.loadImage("img/contender.png");
  map.addImage("contender", contender.data);
  const world_cup = await map.loadImage("img/world_cup.png");
  map.addImage("world_cup", world_cup.data);
  const china = await map.loadImage("img/china.png");
  map.addImage("china", china.data);
  const brazil = await map.loadImage("img/brazil.png");
  map.addImage("brazil", brazil.data);
  const denmark = await map.loadImage("img/denmark.png");
  map.addImage("denmark", denmark.data);
  const france = await map.loadImage("img/france.png");
  map.addImage("france", france.data);
  const germany = await map.loadImage("img/germany.png");
  map.addImage("germany", germany.data);
  const japan = await map.loadImage("img/japan.png");
  map.addImage("japan", japan.data);
  const portugal = await map.loadImage("img/portugal.png");
  map.addImage("portugal", portugal.data);
  const southKorea = await map.loadImage("img/southKorea.png");
  map.addImage("southKorea", southKorea.data);
  const spain = await map.loadImage("img/spain.png");
  map.addImage("spain", spain.data);
  const sweden = await map.loadImage("img/sweden.png");
  map.addImage("sweden", sweden.data);
  const taiwan = await map.loadImage("img/taiwan.png");
  map.addImage("taiwan", taiwan.data);
  const america = await map.loadImage("img/america.png");
  map.addImage("america", america.data);
  const croatia = await map.loadImage("img/croatia.png");
  map.addImage("croatia", croatia.data);
  const india = await map.loadImage("img/india.png");
  map.addImage("india", india.data);
  const nigeria = await map.loadImage("img/nigeria.png");
  map.addImage("nigeria", nigeria.data);
  const slovenia = await map.loadImage("img/slovenia.png");
  map.addImage("slovenia", slovenia.data);
  const switzerland = await map.loadImage("img/switzerland.png");
  map.addImage("switzerland", switzerland.data);
  const austria = await map.loadImage("img/austria.png");
  map.addImage("austria", austria.data);
  const macao = await map.loadImage("img/macao.png");
  map.addImage("macao", macao.data);
  const monaco = await map.loadImage("img/monaco.png");
  map.addImage("monaco", monaco.data);
  const puertoRico = await map.loadImage("img/puertoRico.png");
  map.addImage("puertoRico", puertoRico.data);
  const thailand = await map.loadImage("img/thailand.png");
  map.addImage("thailand", thailand.data);
  const romania = await map.loadImage("img/romania.png");
  map.addImage("romania", romania.data);
}
